KNN:
  - n_neighbors: 5
    weights: uniform

LogisticRegression:
  - max_iter: 200
    C: 0.5
    solver: lbfgs
    random_state: 42

SVM:
  - kernel: linear
    C: 0.2
    gamma: scale
    random_state: 42
    probability: True

DecisionTree:
  - criterion: entropy
    max_depth: 7
    min_samples_split: 5
    random_state: 42

RandomForest:
  - n_estimators: 100
    max_depth: 7
    criterion: entropy
    random_state: 42


NaiveBayes:
  - {}

NeuralNetwork:
  - hidden_layer_sizes: [5,5]
    activation: relu
    solver: adam
    alpha: 0.01
    max_iter: 1200
    random_state: 42
